name: Linux

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04
    env:
      DBFARM: dbfarm

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Install MonetDB
        run: |
            sudo apt-get update -qq
            sudo apt-get install -y software-properties-common curl make
            curl https://www.monetdb.org/downloads/MonetDB-GPG-KEY | sudo apt-key add -
            sudo add-apt-repository 'deb http://dev.monetdb.org/downloads/deb/ focal monetdb'
            sudo apt-get update -qq
            sudo apt-get install -y monetdb5-server
           
      - name: Run MonetDB            
        run: |
            monetdbd create ${{ env.DBFARM }}
            monetdbd start ${{ env.DBFARM }} 
      - name: Create database
        run: |
            bash test/start-monetdb.sh
      - name: Run Unit-Tests
        run: |
            npm t

